name: BuildLinux

on: workflow_dispatch

jobs:
  buildAssets:
    uses: ./.github/workflows/build_assets.yml

  buildLinux-AppImage:
    needs: buildAssets
    runs-on: ubuntu-latest
    env:
      PYTHON_VERSION: "3.12"
      LINUX_TAG: "manylinux_2_28_x86_64"
    steps:
      - name: Python Setup
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          architecture: x64

      - name: Install Packages (pip)
        run: pip install python-appimage

      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          name: nw-assets
          path: novelwriter/assets

      - name: Build AppImage
        id: build
        run: |
          echo "BUILD_VERSION=$(python pkgutils.py version)" >> $GITHUB_OUTPUT
          python pkgutils.py build-appimage --linux-tag $LINUX_TAG --python-version $PYTHON_VERSION

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: novelWriter-${{ steps.build.outputs.BUILD_VERSION }}-Linux-AppImage
          path: dist_appimage/*.AppImage*
          if-no-files-found: error
          retention-days: 14

  buildFlatpak:
    needs: buildAssets
    runs-on: ubuntu-latest
    steps:
      - name: Python Setup
        uses: actions/setup-python@v4
        with:
          python-version: 3
          architecture: x64

      - name: Install Packages (apt, flatpak)
        run: |
          sudo apt update
          sudo apt install flatpak flatpak-builder
          sudo flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo

      - name: Checkout Source
        uses: actions/checkout@v3

      - name: Download Artifacts
        uses: actions/download-artifact@v3
        with:
          name: nw-assets
          path: novelwriter/assets

      - name: Build Flatpak
        id: build
        run: |
          echo "BUILD_VERSION=$(python pkgutils.py version)" >> $GITHUB_OUTPUT
          sudo python pkgutils.py build-flatpak
        
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: novelWriter-${{ steps.build.outputs.BUILD_VERSION }}-linux.flatpak
          path: dist_flatpak/novelWriter-${{ steps.build.outputs.BUILD_VERSION }}-linux.flatpak
          if-no-files-found: error
          retention-days: 1
        